# Generated by Django 4.0.5 on 2022-07-02 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0002_theme_question_answer_document_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='answer',
        ),
    ]
