# Generated by Django 4.0.5 on 2022-07-02 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0003_remove_document_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spapp.answer'),
            preserve_default=False,
        ),
    ]
