# Generated by Django 4.0.5 on 2022-07-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0004_document_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='link',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
