# Generated by Django 4.0.5 on 2022-07-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0005_theme_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
