# Generated by Django 4.0.5 on 2022-07-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0008_rename_document_audio_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audio_answer',
        ),
    ]
