# Generated by Django 4.0.5 on 2022-07-03 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0009_delete_audio_answer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='Audio_answer',
        ),
    ]
