# Generated by Django 4.0.5 on 2022-07-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0010_rename_answer_audio_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio_answer',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='audio_answer',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
