# Generated by Django 4.0.5 on 2022-07-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0011_audio_answer_docfile_alter_audio_answer_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio_answer',
            old_name='docfile',
            new_name='audio_file',
        ),
    ]
