# Generated by Django 4.0.5 on 2022-07-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0012_rename_docfile_audio_answer_audio_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio_answer',
            old_name='title',
            new_name='subtitles',
        ),
    ]
