# Generated by Django 4.0.5 on 2022-07-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0013_rename_title_audio_answer_subtitles'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio_answer',
            name='audio_lenght',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audio_answer',
            name='words_per_second',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audio_answer',
            name='words_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
