# Generated by Django 4.0.5 on 2022-07-16 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0014_audio_answer_audio_lenght_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('upvote', 'upvote'), ('downvote', 'downvote')], max_length=15)),
                ('audio_answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_id_vote', to='spapp.audio_answer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_vote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
