# Generated by Django 4.0.5 on 2022-07-16 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0015_answer_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_vote',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
