# Generated by Django 4.0.5 on 2022-07-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0019_user_reputation'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/theme_image/'),
        ),
    ]
