# Generated by Django 4.0.5 on 2022-07-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0020_theme_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=models.ImageField(upload_to='media/theme_image/'),
        ),
    ]
