# Generated by Django 4.0.5 on 2022-07-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0022_alter_theme_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='link',
        ),
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=models.ImageField(upload_to='theme_image/'),
        ),
    ]
