# Generated by Django 4.0.5 on 2022-07-25 18:46

from django.db import migrations, models
import spapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0023_remove_theme_link_alter_theme_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=models.ImageField(upload_to=spapp.models.theme_directory_path),
        ),
    ]
