# Generated by Django 4.0.5 on 2022-07-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0024_question_answer_counter_alter_theme_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='theme',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
