# Generated by Django 4.0.5 on 2022-08-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0025_question_vote_count_theme_vote_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=160),
        ),
    ]
