# Generated by Django 4.0.5 on 2022-09-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0029_report_status_reputation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_theme_plus', models.IntegerField(default=0)),
                ('rep_theme_minus', models.IntegerField(default=0)),
                ('rep_question_plus', models.IntegerField(default=0)),
                ('rep_question_minus', models.IntegerField(default=0)),
                ('rep_answer_plus', models.IntegerField(default=0)),
                ('rep_answer_minus', models.IntegerField(default=0)),
            ],
        ),
    ]
