# Generated by Django 4.0.5 on 2022-09-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0030_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='reputation',
            name='vote_type',
            field=models.CharField(choices=[('upvote', 'upvote'), ('downvote', 'downvote')], default=1, max_length=15, verbose_name='type'),
            preserve_default=False,
        ),
    ]
