# Generated by Django 4.0.5 on 2022-09-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0031_reputation_vote_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reputation',
            name='vote_type',
            field=models.CharField(choices=[('upvote', 'upvote'), ('downvote', 'downvote')], max_length=15, verbose_name='vote_type'),
        ),
    ]
