# Generated by Django 4.0.5 on 2022-09-07 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0033_alter_report_answer_alter_report_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('upvote', 'upvote'), ('downvote', 'downvote')], max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_id_vote', to='spapp.audio_answer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_user_vote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
