# Generated by Django 4.0.5 on 2022-09-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0036_theme_vote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer_vote',
            options={'verbose_name': 'Vote Answer'},
        ),
        migrations.AlterModelOptions(
            name='question_vote',
            options={'verbose_name': 'Vote Question'},
        ),
        migrations.AlterModelOptions(
            name='theme_vote',
            options={'verbose_name': 'Vote Theme'},
        ),
        migrations.AddField(
            model_name='theme',
            name='questions_count',
            field=models.IntegerField(default=0),
        ),
    ]
